import test from 'node:test';
import assert from 'node:assert/strict';
import { access, mkdtemp, mkdir, readFile, readdir, utimes, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { inspectEditorialHistory, revokeApproval } from '../src/lib/catalogo/history.mjs';

const TOOL = path.resolve('tools/catalogo.mjs'); const ID = 'SEL-000002';
function record() { return { schema_version: '1.0.0', id: ID, slug: 'teste-final', titulo: 'Teste', descricao_curta: 'Teste', identificacao: { pais: 'Brasil', tipo: 'Selo postal', categoria: 'teste', tema: [], valor_facial: { valor: 1, unidade: 'centavo' } }, emissao: { ano: 2000 }, tecnica: {}, catalogos: {}, exemplar: {}, imagens: { frente: `/assets/selos/${ID}/${ID}-frente.webp`, verso: null, card: `/assets/selos/${ID}/${ID}-card.webp`, thumb: null, alt: 'Teste' }, historico: {}, historico_editorial: [], fontes: [], seo: { title: 'Teste', meta_description: 'Teste', canonical_path: '/selos/teste-final' }, aprovacao_humana: { status: 'pendente', decisao: 'pendente', aprovado_por: null, aprovado_em: null, hash_do_registro_aprovado: null, versao_aprovada: null, escopo: 'publicacao_catalogo', observacao: null }, publicacao: { status: 'aguardando_revisao', apto_para_preview: true, apto_para_publicacao: false, motivo: 'teste' }, auditoria: { criado_em: '2026-07-23', ultima_revisao: '2026-07-23', versao: '1.0.0' } }; }
const event = (tipo, responsavel = 'Revisora', ocorrido_em = '2026-07-23T12:00:00.000Z') => ({ tipo, ocorrido_em, responsavel, motivo: ['rejeicao', 'revogacao', 'invalidacao'].includes(tipo) ? 'Motivo' : null, hash: 'a'.repeat(64), versao: '1.0.0' });
async function fixture(value = record()) { const root = await mkdtemp(path.join(tmpdir(), 'selos-final4-')); const file = path.join(root, 'src', 'data', 'selos', `${ID}.json`); for (const dir of [path.dirname(file), path.join(root, 'public', 'assets', 'selos', ID), path.join(root, 'manifests'), path.join(root, 'reports'), path.join(root, 'logs')]) await mkdir(dir, { recursive: true }); await writeFile(file, `${JSON.stringify(value, null, 2)}\n`); await writeFile(path.join(root, 'public', 'assets', 'selos', ID, `${ID}-frente.webp`), 'asset'); await writeFile(path.join(root, 'public', 'assets', 'selos', ID, `${ID}-card.webp`), 'asset'); const reservation = { id: ID, sequence: 2, reserved_at: '2026-07-23T12:00:00.000Z', source: 'teste', status: 'criado', slug: value.slug, created_at: '2026-07-23T12:00:00.000Z', completed_at: '2026-07-23T12:00:01.000Z', failed_at: null, failure_reason: null, cancelado_em: null, cancellation_reason: null }; await writeFile(path.join(root, 'manifests', 'ids.json'), `${JSON.stringify({ schema_version: '2.0.0', prefix: 'SEL', digits: 6, next_sequence: 3, reserved: [reservation] })}\n`); return { root, file }; }
function run(root, command, ...args) { return spawnSync(process.execPath, [TOOL, command, ...args], { cwd: root, encoding: 'utf8' }); }
function assertJsonFailure(result, command, code, exitCode) { assert.equal(result.status, exitCode, result.stdout + result.stderr); assert.equal(result.stderr, ''); const parsed = JSON.parse(result.stdout); assert.equal(parsed.ok, false); assert.equal(parsed.command, command); assert.equal(parsed.error.code, code); assert.equal(result.stdout.trim(), JSON.stringify(parsed, null, 2)); return parsed; }

test('selo:validar --json inválido retorna envelope de falha', async () => { const value = record(); delete value.titulo; const { root } = await fixture(value); assertJsonFailure(run(root, 'selo:validar', ID, '--json'), 'selo:validar', 'VALIDATION_ERROR', 1); });
test('selo:status --json com bloqueios retorna envelope de falha', async () => { const value = record(); value.seo.canonical_path = '/selos/outro'; const { root } = await fixture(value); assertJsonFailure(run(root, 'selo:status', ID, '--json'), 'selo:status', 'VALIDATION_ERROR', 1); });
test('catalogo:auditoria --json com erro retorna envelope de falha', async () => { const value = record(); delete value.titulo; const { root } = await fixture(value); assertJsonFailure(run(root, 'catalogo:auditoria', '--json'), 'catalogo:auditoria', 'VALIDATION_ERROR', 1); });
test('catalogo:status --json com erro retorna envelope de falha', async () => { const value = record(); value.publicacao.status = 'revisao_necessaria'; const { root } = await fixture(value); assertJsonFailure(run(root, 'catalogo:status', '--json'), 'catalogo:status', 'VALIDATION_ERROR', 1); });
test('manutenção bloqueada por lock ativo retorna JSON de falha', async () => { const { root } = await fixture(); await writeFile(path.join(root, 'manifests', 'ids.lock'), JSON.stringify({ pid: process.pid, timestamp: new Date().toISOString(), command: 'teste', token: 'ativo' })); assertJsonFailure(run(root, 'catalogo:manutencao', '--limpar', '--json'), 'catalogo:manutencao', 'INTEGRITY_ERROR', 3); });
test('comando inexistente e aprovação falha retornam JSON puro', async () => { const { root } = await fixture(); assertJsonFailure(run(root, 'inexistente', '--json'), 'inexistente', 'CLI_USAGE', 2); assertJsonFailure(run(root, 'selo:aprovar', ID, '--json'), 'selo:aprovar', 'CLI_USAGE', 2); });

test('grafo dos módulos não possui ciclo estático', async () => { const dir = path.resolve('src/lib/catalogo'); const names = (await readdir(dir)).filter((name) => name.endsWith('.mjs')); const graph = new Map(); for (const name of names) { const source = await readFile(path.join(dir, name), 'utf8'); graph.set(name, [...source.matchAll(/from ['"]\.\/([^'"]+\.mjs)['"]/g)].map((match) => match[1]).filter((item) => names.includes(item))); } const visiting = new Set(); const visited = new Set(); function visit(name) { if (visiting.has(name)) throw new Error(`ciclo: ${name}`); if (visited.has(name)) return; visiting.add(name); for (const child of graph.get(name) ?? []) visit(child); visiting.delete(name); visited.add(name); } for (const name of names) visit(name); });
test('commands não reimplementa domínios extraídos', async () => { const source = await readFile(path.resolve('src/lib/catalogo/commands.mjs'), 'utf8'); for (const forbidden of ['function inspectRecordFiles', 'function inspectManifest', 'function operationalResidues', 'function createStampTransaction', 'function auditCatalog']) assert.doesNotMatch(source, new RegExp(forbidden)); });

test('histórico detecta aprovado, publicado e revisão necessária incompatíveis', () => { const approved = record(); approved.publicacao.status = 'aprovado'; approved.aprovacao_humana.status = 'aprovado'; approved.aprovacao_humana.decisao = 'aprovado'; approved.historico_editorial = [event('aprovacao'), event('revogacao', 'R2', '2026-07-23T13:00:00.000Z')]; assert.ok(inspectEditorialHistory(approved).errors.some((item) => /status aprovado/.test(item))); const published = structuredClone(approved); published.publicacao.status = 'publicado'; assert.ok(inspectEditorialHistory(published).errors.some((item) => /status publicado/.test(item))); const review = record(); review.publicacao.status = 'revisao_necessaria'; assert.ok(inspectEditorialHistory(review).errors.some((item) => /revisão necessária/.test(item))); });
test('histórico detecta publicação/invalidação sem aprovação e eventos consecutivos', () => { const value = record(); value.historico_editorial = [event('publicacao')]; assert.ok(inspectEditorialHistory(value).errors.some((item) => /publicação sem aprovação anterior/.test(item))); value.historico_editorial = [event('invalidacao')]; assert.ok(inspectEditorialHistory(value).errors.some((item) => /invalidação sem aprovação anterior/.test(item))); value.historico_editorial = [event('aprovacao'), event('aprovacao', 'R2', '2026-07-23T13:00:00.000Z')]; assert.ok(inspectEditorialHistory(value).errors.some((item) => /aprovações consecutivas/.test(item))); value.historico_editorial = [event('aprovacao'), event('publicacao', 'R', '2026-07-23T13:00:00.000Z'), event('publicacao', 'R', '2026-07-23T14:00:00.000Z')]; assert.ok(inspectEditorialHistory(value).errors.some((item) => /publicações consecutivas/.test(item))); });
test('revogação manual e automática usam domínio comum e preservam histórico', () => { const value = record(); value.aprovacao_humana = { ...value.aprovacao_humana, status: 'aprovado', decisao: 'aprovado', aprovado_por: 'Original', aprovado_em: '2026-07-23T11:00:00.000Z', hash_do_registro_aprovado: 'a'.repeat(64), versao_aprovada: '1.0.0' }; value.historico_editorial = [event('aprovacao', 'Original')]; const manual = revokeApproval(value, { reviewer: 'Manual', reason: 'Motivo', type: 'revogacao', currentHash: 'b'.repeat(64) }); const automatic = revokeApproval(value, { reviewer: 'pipeline', reason: 'Hash', type: 'invalidacao', currentHash: 'c'.repeat(64) }); assert.equal(manual.aprovacao_humana.aprovado_por, 'Original'); assert.equal(automatic.aprovacao_humana.hash_do_registro_aprovado, 'a'.repeat(64)); assert.deepEqual(manual.historico_editorial.map((item) => item.tipo), ['aprovacao', 'revogacao']); assert.deepEqual(automatic.historico_editorial.map((item) => item.tipo), ['aprovacao', 'invalidacao']); });

test('manutenção diagnostica relatório e linha JSONL ilegíveis', async () => { const { root } = await fixture(); await writeFile(path.join(root, 'reports', 'quebrado.json'), '{'); await writeFile(path.join(root, 'logs', 'pipeline.jsonl'), '{invalido}\n'); const result = run(root, 'catalogo:manutencao', '--dry-run', '--json'); assert.equal(result.status, 0); const data = JSON.parse(result.stdout).data; assert.equal(data.invalid_reports.length, 1); assert.equal(data.invalid_log_lines.length, 1); });
test('manutenção detecta diretório removal e temporário antigo em assets', async () => { const { root } = await fixture(); const removal = path.join(root, 'public', 'assets', 'selos', '.removal-antigo'); const temporary = path.join(root, 'public', 'assets', 'selos', 'arquivo.transaction-antigo'); await mkdir(removal); await writeFile(temporary, 'x'); const old = new Date(Date.now() - 120_000); await utimes(removal, old, old); await utimes(temporary, old, old); const data = JSON.parse(run(root, 'catalogo:manutencao', '--dry-run', '--json').stdout).data; assert.ok(data.residues.some((item) => item.kind === 'removal_directory')); assert.ok(data.residues.some((item) => item.path.includes('transaction-antigo'))); });
test('limpeza preserva temporário recente e asset válido', async () => { const { root } = await fixture(); const recent = path.join(root, 'public', 'assets', 'selos', 'recent.tmp'); await writeFile(recent, 'x'); const valid = path.join(root, 'public', 'assets', 'selos', ID, `${ID}-frente.webp`); const result = run(root, 'catalogo:manutencao', '--limpar', '--json'); assert.equal(result.status, 3); await access(recent); await access(valid); });
test('limpeza antiga gera log padronizado', async () => { const { root } = await fixture(); const oldFile = path.join(root, 'manifests', 'old.tmp'); await writeFile(oldFile, 'x'); const old = new Date(Date.now() - 120_000); await utimes(oldFile, old, old); const result = run(root, 'catalogo:manutencao', '--limpar', '--json'); assert.equal(result.status, 0, result.stdout); const log = (await readFile(path.join(root, 'logs', 'pipeline.jsonl'), 'utf8')).trim().split('\n').map(JSON.parse); const removed = log.find((item) => item.event === 'maintenance_removed'); assert.ok(removed.transaction_id); assert.equal(removed.command, 'catalogo:manutencao'); assert.equal(typeof removed.pid, 'number'); assert.equal(removed.status_anterior, undefined); });