import path from 'node:path';
import { recordHash } from '../selo-validation.mjs';
import { assetErrors, validateAssets } from './assets.mjs';
import { auditCatalog, auditOne, validateRecord } from './audit.mjs';
import { ApprovalError, UsageError } from './errors.mjs';
import { appendEditorialEvent, revokeApproval } from './history.mjs';
import { writeJsonAtomic } from './io.mjs';
import { appendLog, setLogContext } from './logging.mjs';
import { runMaintenance } from './maintenance.mjs';
import { REPORT_DIR } from './paths.mjs';
import { loadRecords, normalizeSlug, resolveRecord } from './records.mjs';
import { getCatalogStatus, getStampStatus } from './status.mjs';
import { createStampTransaction, transactionIdFor } from './transactions.mjs';

let command = null; let args = { _: [] };
const now = () => new Date().toISOString(); const today = () => new Date().toISOString().slice(0, 10);
export function parseArgs(values) { const parsed = { _: [] }; for (let index = 0; index < values.length; index += 1) { const token = values[index]; if (!token.startsWith('--')) { parsed._.push(token); continue; } const key = token.slice(2); const next = values[index + 1]; if (!next || next.startsWith('--')) parsed[key] = true; else { parsed[key] = next; index += 1; } } return parsed; }
const success = (data = {}, warnings = []) => ({ ok: true, data, warnings, exitCode: 0 });
const failure = (code, message, data = {}, exitCode = 1, details = {}) => ({ ok: false, data, warnings: [], error: { code, message, details }, exitCode });
function requiredArg(name, usage) { const value = typeof args[name] === 'string' ? args[name].trim() : ''; if (!value) throw new UsageError(usage, { details: { missing: name } }); return value; }

async function seloNovo() {
  const slug = normalizeSlug(args.slug); const title = typeof args.titulo === 'string' ? args.titulo.trim() : '';
  if (!slug || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug) || !title) throw new UsageError('Uso: npm run selo:novo -- --slug <slug válido> --titulo <título>');
  try { const data = await createStampTransaction({ slug, title }); await appendLog('selo_novo', data); console.log(`${data.id} reservado e rascunho criado.`); return success(data); }
  catch (error) { await appendLog('selo_novo_falha', { slug, error_code: error.code ?? 'TRANSACTION_ERROR', message: error.message }); throw error; }
}
async function seloPreparar() { const { record } = await resolveRecord(args._[0]); const report = await auditOne(record.id); const data = { ...report, stage: 'preparacao', ready_for_review: report.errors.length === 0 && report.assets.every((asset) => asset.path_valid && asset.exists) }; await writeJsonAtomic(path.join(REPORT_DIR, `${record.id}-preparacao.json`), data); await appendLog('selo_preparar', { id: record.id, message: `ready_for_review=${data.ready_for_review}` }); console.log(JSON.stringify(data, null, 2)); return data.ready_for_review ? success(data, data.warnings) : failure('VALIDATION_ERROR', 'Registro não está pronto para revisão.', data, 1, { errors: data.errors }); }
async function seloValidar() { const targets = args._[0] ? [await resolveRecord(args._[0])] : await loadRecords(); const data = []; for (const { path: filePath, record } of targets) { const validation = validateRecord(record, filePath); const assets = await validateAssets(record); const asset_errors = assetErrors(assets); data.push({ id: record.id, valid: validation.errors.length === 0 && asset_errors.length === 0, structural_errors: validation.structural_errors, semantic_errors: validation.semantic_errors, editorial_errors: validation.editorial_errors, file_errors: validation.file_errors, asset_errors, errors: [...validation.errors, ...asset_errors], warnings: validation.warnings }); } console.log(JSON.stringify(data, null, 2)); const invalid = data.filter((item) => !item.valid); return invalid.length ? failure('VALIDATION_ERROR', 'Validação do registro falhou.', data, 1, { invalid }) : success(data); }
async function seloRevisao() { const { path: filePath, record } = await resolveRecord(args._[0]); if (record.publicacao.status === 'publicado') throw new ApprovalError('Registro publicado não pode retornar à revisão por este comando.'); const candidate = structuredClone(record); candidate.aprovacao_humana = { status: 'pendente', decisao: 'pendente', aprovado_por: null, aprovado_em: null, hash_do_registro_aprovado: null, versao_aprovada: null, escopo: 'publicacao_catalogo', observacao: args.observacao || null }; candidate.publicacao.status = 'aguardando_revisao'; candidate.publicacao.apto_para_publicacao = false; candidate.publicacao.motivo = 'aguardando aprovação humana para publicação'; candidate.auditoria.ultima_revisao = today(); const validation = validateRecord(candidate, filePath); if (validation.errors.length) throw new ApprovalError(`REVISÃO BLOQUEADA:\n${validation.errors.join('\n')}`, { details: validation }); await writeJsonAtomic(filePath, candidate); await appendLog('selo_revisao', { id: candidate.id, slug: candidate.slug, previous_status: record.publicacao.status, new_status: candidate.publicacao.status, version: candidate.auditoria.versao }); console.log(`${candidate.id} encaminhado para revisão humana.`); return success({ id: candidate.id }); }
async function seloAprovar() { const reviewer = requiredArg('revisor', 'Uso: npm run selo:aprovar -- <ID> --revisor <nome não vazio> [--observacao <texto>]'); const { path: filePath, record } = await resolveRecord(args._[0]); if (record.publicacao.status === 'publicado') throw new ApprovalError('Registro já publicado.'); const candidate = structuredClone(record); candidate.publicacao.status = 'aprovado'; candidate.publicacao.apto_para_publicacao = false; candidate.publicacao.motivo = 'registro aprovado por revisão humana; validação técnica e publicação pendentes'; candidate.auditoria.ultima_revisao = today(); candidate.aprovacao_humana = { ...candidate.aprovacao_humana, status: 'aprovado', decisao: 'aprovado', aprovado_por: reviewer, aprovado_em: now(), hash_do_registro_aprovado: null, versao_aprovada: candidate.auditoria.versao, escopo: 'publicacao_catalogo', observacao: args.observacao || null }; candidate.aprovacao_humana.hash_do_registro_aprovado = recordHash(candidate); appendEditorialEvent(candidate, { tipo: 'aprovacao', responsavel: reviewer, motivo: args.observacao || null, hash: candidate.aprovacao_humana.hash_do_registro_aprovado, versao: candidate.auditoria.versao }); const errors = validateRecord(candidate, filePath).errors; if (errors.length) throw new ApprovalError(`APROVAÇÃO BLOQUEADA:\n${errors.join('\n')}`, { details: { errors } }); await writeJsonAtomic(filePath, candidate); await appendLog('selo_aprovar', { id: candidate.id, slug: candidate.slug, reviewer, previous_status: record.publicacao.status, new_status: candidate.publicacao.status, hash: candidate.aprovacao_humana.hash_do_registro_aprovado, version: candidate.auditoria.versao }); console.log(`${candidate.id} aprovado por ${reviewer}.`); return success({ id: candidate.id, reviewer }); }
async function persistRevocation(filePath, record, options) { const candidate = revokeApproval(record, options); candidate.auditoria.ultima_revisao = today(); const errors = validateRecord(candidate, filePath).errors; if (errors.length) throw new ApprovalError(`${options.type === 'invalidacao' ? 'INVALIDAÇÃO' : 'REVOGAÇÃO'} BLOQUEADA:\n${errors.join('\n')}`, { details: { errors } }); await writeJsonAtomic(filePath, candidate); return candidate; }
async function seloRejeitar() { const reviewer = requiredArg('revisor', 'Uso: npm run selo:rejeitar -- <ID> --revisor <nome> --motivo <motivo>'); const reason = requiredArg('motivo', 'Uso: npm run selo:rejeitar -- <ID> --revisor <nome> --motivo <motivo>'); const { path: filePath, record } = await resolveRecord(args._[0]); const candidate = structuredClone(record); const occurredAt = now(); candidate.aprovacao_humana = { ...(candidate.aprovacao_humana ?? {}), status: 'rejeitado', decisao: 'rejeitado', rejeitado_por: reviewer, rejeitado_em: occurredAt, motivo_rejeicao: reason, escopo: 'publicacao_catalogo', aprovado_por: candidate.aprovacao_humana?.aprovado_por ?? null, aprovado_em: candidate.aprovacao_humana?.aprovado_em ?? null, hash_do_registro_aprovado: candidate.aprovacao_humana?.hash_do_registro_aprovado ?? null, versao_aprovada: candidate.aprovacao_humana?.versao_aprovada ?? null }; candidate.publicacao.status = 'revisao_necessaria'; candidate.publicacao.apto_para_publicacao = false; candidate.publicacao.motivo = reason; candidate.auditoria.ultima_revisao = today(); appendEditorialEvent(candidate, { tipo: 'rejeicao', responsavel: reviewer, motivo: reason, hash: recordHash(candidate), versao: candidate.auditoria.versao, ocorrido_em: occurredAt }); const errors = validateRecord(candidate, filePath).errors; if (errors.length) throw new ApprovalError(`REJEIÇÃO BLOQUEADA:\n${errors.join('\n')}`, { details: { errors } }); await writeJsonAtomic(filePath, candidate); await appendLog('selo_rejeitar', { id: candidate.id, slug: candidate.slug, reviewer, previous_status: record.publicacao.status, new_status: candidate.publicacao.status, hash: recordHash(candidate), version: candidate.auditoria.versao }); console.log(`${candidate.id} rejeitado por ${reviewer}.`); return success({ id: candidate.id, reviewer }); }
async function seloRevogar() { const reviewer = requiredArg('revisor', 'Uso: npm run selo:revogar -- <ID> --revisor <nome> --motivo <motivo>'); const reason = requiredArg('motivo', 'Uso: npm run selo:revogar -- <ID> --revisor <nome> --motivo <motivo>'); const { path: filePath, record } = await resolveRecord(args._[0]); if (record.aprovacao_humana?.status !== 'aprovado' || record.aprovacao_humana?.decisao !== 'aprovado') throw new ApprovalError('REVOGAÇÃO BLOQUEADA: apenas aprovação ativa pode ser revogada.'); const candidate = await persistRevocation(filePath, record, { reviewer, reason, type: 'revogacao', currentHash: recordHash(record), occurredAt: now() }); await appendLog('selo_revogar', { id: candidate.id, slug: candidate.slug, reviewer, previous_status: record.publicacao.status, new_status: candidate.publicacao.status, hash: recordHash(candidate), version: candidate.auditoria.versao }); console.log(`${candidate.id} teve a aprovação revogada por ${reviewer}.`); return success({ id: candidate.id, reviewer }); }
async function seloPublicar() { const { path: filePath, record } = await resolveRecord(args._[0]); const approval = record.aprovacao_humana; const valid = approval?.status === 'aprovado' && approval?.decisao === 'aprovado' && approval?.aprovado_por && approval?.aprovado_em && approval?.hash_do_registro_aprovado && approval?.versao_aprovada; if (!valid) throw new ApprovalError('PUBLICAÇÃO BLOQUEADA: aprovação humana válida é obrigatória.'); const currentHash = recordHash(record); if (currentHash !== approval.hash_do_registro_aprovado || record.auditoria?.versao !== approval.versao_aprovada) { const candidate = await persistRevocation(filePath, record, { reviewer: 'pipeline', reason: 'conteúdo alterado após aprovação', type: 'invalidacao', currentHash, occurredAt: now() }); await appendLog('aprovacao_invalidada', { id: candidate.id, slug: candidate.slug, reviewer: 'pipeline', previous_status: record.publicacao.status, new_status: candidate.publicacao.status, hash: currentHash, version: candidate.auditoria.versao }); throw new ApprovalError('PUBLICAÇÃO BLOQUEADA: conteúdo ou versão diverge da aprovação; aprovação invalidada.'); } const assets = await validateAssets(record); const preflight = [...validateRecord(record, filePath).errors, ...assetErrors(assets)]; if (preflight.length) throw new ApprovalError(`PUBLICAÇÃO BLOQUEADA:\n${preflight.join('\n')}`, { details: { errors: preflight } }); const candidate = structuredClone(record); candidate.publicacao.status = 'publicado'; candidate.publicacao.apto_para_preview = true; candidate.publicacao.apto_para_publicacao = true; candidate.publicacao.motivo = 'registro homologado e aprovado para publicação'; candidate.auditoria.ultima_revisao = today(); appendEditorialEvent(candidate, { tipo: 'publicacao', responsavel: approval.aprovado_por, motivo: candidate.publicacao.motivo, hash: currentHash, versao: candidate.auditoria.versao }); const finalErrors = validateRecord(candidate, filePath).errors; if (finalErrors.length) throw new ApprovalError(`PUBLICAÇÃO BLOQUEADA:\n${finalErrors.join('\n')}`, { details: { errors: finalErrors } }); await writeJsonAtomic(filePath, candidate); await appendLog('selo_publicar', { id: candidate.id, slug: candidate.slug, reviewer: approval.aprovado_por, previous_status: record.publicacao.status, new_status: candidate.publicacao.status, hash: currentHash, version: candidate.auditoria.versao }); console.log(`${candidate.id} marcado como publicado.`); return success({ id: candidate.id }); }
async function seloAuditoria() { const data = await auditOne(args._[0]); await appendLog('selo_auditoria', { id: data.id, slug: data.slug, message: `valid=${data.valid}` }); console.log(JSON.stringify(data, null, 2)); return data.valid ? success(data, data.warnings) : failure('VALIDATION_ERROR', 'Auditoria do registro falhou.', data, 1, { errors: data.errors }); }
async function catalogoAuditoria() { const data = await auditCatalog(); await appendLog('catalogo_auditoria', { message: `total=${data.total}; valid=${data.valid}; errors=${data.errors.length}; warnings=${data.warnings.length}` }); console.log(JSON.stringify(data, null, 2)); return data.valid ? success(data, data.warnings) : failure('VALIDATION_ERROR', 'Auditoria do catálogo falhou.', data, 1, { errors: data.errors }); }
async function seloStatus() { const result = await getStampStatus(args._[0]); console.log(JSON.stringify(result.data, null, 2)); return result.errors.length ? failure('VALIDATION_ERROR', 'Registro possui bloqueios.', result.data, 1, { errors: result.errors }) : success(result.data, result.warnings); }
async function catalogoStatus() { const result = await getCatalogStatus(); console.log(JSON.stringify(result.data, null, 2)); return result.errors.length ? failure('VALIDATION_ERROR', 'Catálogo possui erros.', result.data, 1, { errors: result.errors }) : success(result.data, result.warnings); }
async function catalogoManutencao() { const clean = args.limpar === true; const dryRun = args['dry-run'] === true || !clean; const data = await runMaintenance({ clean, dryRun }); await appendLog('catalogo_manutencao', { message: `mode=${data.mode}; removed=${data.removed.length}; blocked=${data.blocked.length}` }); console.log(JSON.stringify(data, null, 2)); return clean && data.blocked.length ? failure('INTEGRITY_ERROR', 'Limpeza bloqueada por itens inseguros.', data, 3, { blocked: data.blocked }) : success(data); }

const commands = { 'selo:novo': seloNovo, 'selo:preparar': seloPreparar, 'selo:validar': seloValidar, 'selo:revisao': seloRevisao, 'selo:aprovar': seloAprovar, 'selo:rejeitar': seloRejeitar, 'selo:revogar': seloRevogar, 'selo:status': seloStatus, 'selo:publicar': seloPublicar, 'selo:auditoria': seloAuditoria, 'catalogo:auditoria': catalogoAuditoria, 'catalogo:status': catalogoStatus, 'catalogo:manutencao': catalogoManutencao };
export function availableCommands() { return Object.keys(commands); }
export async function executeCommand(selectedCommand, argv = []) { command = selectedCommand; args = parseArgs(argv); const transaction_id = transactionIdFor(command); setLogContext({ command, transaction_id }); if (!commands[command]) throw new UsageError(`Comando inválido. Disponíveis: ${Object.keys(commands).join(', ')}`, { details: { available: Object.keys(commands) } }); return commands[command](); }
export { appendLog } from './logging.mjs';